package SH_SCRUD;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Shorlo
 */
public class SH_SCRUDJFrameForm extends javax.swing.JFrame 
{
    public static final String URL = "jdbc:mysql://localhost:3306/escuela";
    public static final String USERNAME = "root";
    public static final String PASSWORD = "1234";
    
    PreparedStatement ps;
    ResultSet rs;
    
   /**
    * Connection code
    */
    public static Connection getConnection()
    {
        Connection con = null;
        
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = (Connection) DriverManager.getConnection(URL, USERNAME, PASSWORD);
            JOptionPane.showMessageDialog(null,"Connection succsess!!");
        }
        catch(Exception error)
        {
            System.err.println("Get connection failed!!" + error);
        }
        return con;
    }
    
    private void clearBoxes()
    {
        txtClave.setText(null);
        txtName.setText(null);
        txtEmail.setText(null);
        txtAddress.setText(null);
        cmbGender.setSelectedIndex(0);
    }
    /**
     * Creates new form SH_SCRUDJFrameForm
     */
    public SH_SCRUDJFrameForm() 
    { 
        initComponents();
        txtId.setVisible(false);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbGender = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        btnModifiy = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnClean = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Clave:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Email:");

        jLabel4.setText("Domicilio:");

        jLabel5.setText("Genero:");

        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female", " " }));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnModifiy.setText("Modify");
        btnModifiy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifiyActionPerformed(evt);
            }
        });

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnClean.setText("Clean");
        btnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        txtId.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSave)
                        .addGap(18, 18, 18)
                        .addComponent(btnModifiy)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemove)
                        .addGap(18, 18, 18)
                        .addComponent(btnClean, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtName)
                            .addComponent(txtEmail)
                            .addComponent(txtAddress)
                            .addComponent(cmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtId)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearch)))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(cmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnModifiy)
                    .addComponent(btnRemove)
                    .addComponent(btnClean))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * 
     * @param evt 
     */
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        
        Connection con = null;
        
        try
        {
            con = getConnection();
            ps = con.prepareStatement("SELECT * FROM alumnos WHERE clave = ?");
            
            ps.setString(1, txtClave.getText());
            
            rs = ps.executeQuery();
            
            if(rs.next())
            {
                txtId.setText(rs.getString("id"));
                txtName.setText(rs.getString("nombre"));
                txtEmail.setText(rs.getString("email"));
                txtAddress.setText(rs.getString("domicilio"));
                cmbGender.setSelectedItem(rs.getString("genero"));  
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Id Student wrong!!");
            }
        }
        catch (Exception error)
        {
            System.err.println(error);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * Save info from the form.
     */
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        Connection con = null;
        try
        {
            /**
              * Connection open
              */
            con = getConnection();
            ps = con.prepareStatement("INSERT INTO alumnos (clave, nombre, email, domicilio, genero) VALUES (?, ?, ?, ?, ?)"); // SQL stament
            /**
              * Add values from text form
              */
            ps.setString(1, txtClave.getText());                        // clave
            ps.setString(2, txtName.getText());                         // nombre
            ps.setString(3, txtEmail.getText());                        // email
            ps.setString(4, txtAddress.getText());                      // domicilio
            ps.setString(5, cmbGender.getSelectedItem().toString());    // genero     
            /**
              * Keep result of the execution of query and evaluate if works or not
              */
            int res = ps.executeUpdate();
            
            if (res > 0)
            {
                JOptionPane.showMessageDialog(null, "Student saved!!");
                clearBoxes();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Error saving student!!");
                clearBoxes();
            }
            /**
              * Connection closed
              */
            con.close();
        }
        catch (Exception error)
        {
            System.err.println(error);
        }  
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnModifiyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifiyActionPerformed
        // TODO add your handling code here:
        Connection con = null;
        try
        {
            /**
              * Connection open
              */
            con = getConnection();
            ps = con.prepareStatement("UPDATE alumnos SET clave = ?, nombre = ?, email = ?, domicilio = ?, genero = ? WHERE id=?"); // SQL stament
            /**
              * Add values from text form
              */
            ps.setString(1, txtClave.getText());                        // clave
            ps.setString(2, txtName.getText());                         // nombre
            ps.setString(3, txtEmail.getText());                        // email
            ps.setString(4, txtAddress.getText());                      // domicilio
            ps.setString(5, cmbGender.getSelectedItem().toString());    // genero     
            ps.setString(6, txtId.getText());
            /**
              * Keep result of the execution of query and evaluate if works or not
              */
            int res = ps.executeUpdate();

            if (res > 0)
            {
                JOptionPane.showMessageDialog(null, "Student modified!!");
                clearBoxes();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Error modifying student!!");
                clearBoxes();
            }
            /**
              * Connection closed
              */
            con.close();
        }
        catch (Exception error)
        {
            System.err.println(error);
        }     
        
        
    }//GEN-LAST:event_btnModifiyActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        Connection con = null;
        try
        {
            /**
              * Connection open
              */
            con = getConnection();
            ps = con.prepareStatement("DELETE FROM alumnos WHERE id=?"); // SQL stament
            
            ps.setInt(1, Integer.parseInt(txtId.getText()));
            /**
              * Keep result of the execution of query and evaluate if works or not
              */
            int res = ps.executeUpdate();

            if (res > 0)
            {
                JOptionPane.showMessageDialog(null, "Student deleted!!");
                clearBoxes();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Error deleting student!!");
                clearBoxes();
            }
            /**
              * Connection closed
              */
            con.close();
        }
        catch (Exception error)
        {
            System.err.println(error);
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
        // TODO add your handling code here:
        clearBoxes();
    }//GEN-LAST:event_btnCleanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SH_SCRUDJFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SH_SCRUDJFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SH_SCRUDJFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SH_SCRUDJFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                new SH_SCRUDJFrameForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnModifiy;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cmbGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
